package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"time"
)

type AutoGenerated struct {
	Usdbrl struct {
		Code   string `json:"code"`
		Codein string `json:"codein"`
		Name   string `json:"name"`
		Bid    string `json:"bid"`
	} `json:"USDBRL"`
}

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Millisecond)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, "GET", "http://localhost:8080/cotacao", nil)
	if err != nil {
		return
	}

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return
	}

	var exchangeRate AutoGenerated
	if err := json.Unmarshal(body, &exchangeRate); err != nil {
		return
	}

	cotacao := fmt.Sprintf("Dólar: %s", exchangeRate.Usdbrl.Bid)
	if err := ioutil.WriteFile("cotacao.txt", []byte(cotacao), 0644); err != nil {
		fmt.Println("Erro ao salvar o arquivo:", err)
		return
	}

	fmt.Println("Cotação salva com sucesso:", cotacao)
}
