package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

type AutoGenerated struct {
	Usdbrl struct {
		Code   string `json:"code"`
		Codein string `json:"codein"`
		Name   string `json:"name"`
		Bid    string `json:"bid"`
	} `json:"USDBRL"`
}

func main() {
	db, err := sql.Open("sqlite3", "./cotacoes.db")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	createTableSQL := `CREATE TABLE IF NOT EXISTS cotacoes (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		valor TEXT,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);`
	if _, err := db.Exec(createTableSQL); err != nil {
		log.Fatal(err)
	}

	http.HandleFunc("/cotacao", func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), 200*time.Millisecond)
		defer cancel()

		exchangeRate, err := getExchangeRate(ctx)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		if err := saveToDatabase(ctx, db, exchangeRate.Usdbrl.Bid); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(exchangeRate)
	})

	log.Println("Server is listening on port 8080...")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}

func getExchangeRate(ctx context.Context) (AutoGenerated, error) {
	var exchangeRate AutoGenerated

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "https://economia.awesomeapi.com.br/json/last/USD-BRL", nil)

	if err != nil {
		return exchangeRate, err
	}

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return exchangeRate, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return exchangeRate, fmt.Errorf("falha ao obter a resposta: %s", resp.Status)
	}

	if err := json.NewDecoder(resp.Body).Decode(&exchangeRate); err != nil {
		return exchangeRate, err
	}

	return exchangeRate, nil
}

func saveToDatabase(ctx context.Context, db *sql.DB, value string) error {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Millisecond)
	defer cancel()

	_, err := db.ExecContext(ctx, "INSERT INTO cotacoes (valor) VALUES (?)", value)

	return err
}
